export const ENV = {
    API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
    CLIENT_BASE_URL: process.env.NEXT_PUBLIC_CLIENT_BASE_URL,
    GIPHY_API_KEY: process.env.NEXT_PUBLIC_GIPHY_API_KEY,
    STREAM_API_KEY: process.env.NEXT_PUBLIC_STREAM_API_KEY,
    STREAM_SECRET_KEY: process.env.STREAM_SECRET_KEY,
};
